### ISSUE TITLE
Components with templateUrl

### ISSUE THREAD

**Issue by Bnaya** [robisim74/angular-library-starter#1]
Hey

First, thank you very much for that project!

Is it possible to use it to make Components with external templates? (templateUrl)

**Comment by robisim74** [comment]
Hi,

no as is. You should customize the configuration.

Greetings

**Comment by Bnaya** [comment]
Do you know any good example for that?

Thanks!

**Comment by robisim74** [comment]
All the libraries that I know don't use `templateUrl`, they use inline `template` whether implement components.
I know only official Material that uses that: https://github.com/angular/material2/tree/master/tools/gulp/packaging

**Comment by achieverprince** [comment]
@Bnaya 

Why cant you use "external templates" in the components ?

**Comment by orizens** [comment]
@robisim74 
we can take a similar approach as the angular-cli [does it with @ngtools webpack loader](https://github.com/angular/angular-cli/blob/c268b5889fa66c3f8f925edf11115cf1c03cbdad/packages/%40ngtools/webpack/src/loader.ts#L310)
a similar step would need to be added to the build.js before or while compiling with ts.

**Comment by robisim74** [comment]
>Component libraries are typically implemented using stylesheets and html templates stored in separate files. While it's not required, we suggest that component authors inline the templates and stylesheets into their FESM files as well as *.metadata.json files by replacing the stylesheetUrls and templateUrl with stylesheets and template metadata properties respectively. This simplifies consumption of the components by application developers.

https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#heading=h.dhi53tt0wmgv

Moreover, using _Angular language service_ you have the intellisense also working exclusively in *.ts files.

Moving towards external templates and css would require a lot of tools if you want to avoid incompatibilities, and unless you are planning to build a library like Angular material (tools: https://github.com/angular/material2/tree/master/tools/gulp/packaging) I do not see the need for it.

In my opinion, maintaining an Angular library requires a lot of effort because of the constant changes: more the building process is complicated, more problems will be.

**Comment by joshwiens** [comment]
Got to agree with @robisim74 here. Short of creating a lib the size & scope of something like Material2, there is no need to go outside of the component with styles & templates.

In 90% of the cases, if your component is too large when you are inlining it's probably time to start breaking up that component.

**Comment by maximelafarie** [comment]
@robisim74 In angular material, they're using `templateUrl` and `styleUrls`: https://github.com/angular/material2/blob/master/src/lib/dialog/dialog-container.ts

**Comment by robisim74** [comment]
As I already explained above: https://github.com/robisim74/angular-library-starter/issues/1#issuecomment-283284166, I know that Angular Material has built its own configuration to use templateUrl and stylesUrls: but you should also give a look into their tools to do it: https://github.com/angular/material2/tree/master/tools/package-tools (this link changes every time...)

If it is so important to use them, there are other starters who use webpack, instead of rollup and the building process of Angular libraries.

Greetings

**Comment by maximelafarie** [comment]
@robisim74 Thank you for these great explanations. 😉 I have some questions to ask to you about components's functions that are not accessible when compiled, is there any gitter or something else to exchange?

**Comment by robisim74** [comment]
Another question, another issue.

**Comment by paullryan** [comment]
@robisim74 Here's my version of build.js that does the inlining, it's a bit dirty but it's a start

```js
"use strict";

const shell = require('shelljs');
const chalk = require('chalk');
const cpx = require('cpx');
const replace = require('replace');
const rimraf = require('rimraf');

const PACKAGE = `time-picker`;
const NPM_DIR = `dist`;
const ESM2015_DIR = `${NPM_DIR}/esm2015`;
const ESM5_DIR = `${NPM_DIR}/esm5`;
const BUNDLES_DIR = `${NPM_DIR}/bundles`;
const OUT_DIR_ESM5 = `${NPM_DIR}/package/esm5`;

shell.echo(`Start building...`);

rimraf.sync(`${NPM_DIR}/*`);
shell.mkdir(`-p`, `./${ESM2015_DIR}`);
shell.mkdir(`-p`, `./${ESM5_DIR}`);
shell.mkdir(`-p`, `./${BUNDLES_DIR}`);

/* TSLint with Codelyzer */
// https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts
// https://github.com/mgechev/codelyzer
shell.echo(`Start TSLint`);
shell.exec(`tslint -c tslint.json -t stylish src/**/*.ts`);
shell.echo(chalk.green(`TSLint completed`));

/* AoT compilation */
shell.echo(`Start AoT compilation`);
if (shell.exec(`ngc -p tsconfig-build.json`).code !== 0) {
    shell.echo(chalk.red(`Error: AoT compilation failed`));
    shell.exit(1);
}
shell.echo(chalk.green(`AoT compilation completed`));

/* Inline Styles */
cpx.copySync('./src/**/*.scss', `${NPM_DIR}/src`);
cpx.copySync('./src/**/*.html', `${NPM_DIR}/src`);

shell.exec(`node_modules/.bin/node-sass -r ${NPM_DIR} -o ${NPM_DIR}`);

replace({
    regex: '.scss',
    replacement: '.css',
    paths: ['./dist'],
    recursive: true,
    silent: true
});

shell.exec('node_modules/.bin/ng2-inline -b dist -s -r -o .  \"dist/**/*.js\"');

/* BUNDLING PACKAGE */
shell.echo(`Start bundling`);
shell.echo(`Rollup package`);
if (shell.exec(`rollup -c rollup.es.config.js -i ${NPM_DIR}/${PACKAGE}.js -o ${ESM2015_DIR}/${PACKAGE}.js`).code !== 0) {
    shell.echo(chalk.red(`Error: Rollup package failed`));
    shell.exit(1);
}

shell.echo(`Produce ESM5 version`);
shell.exec(`ngc -p tsconfig-build.json --target es5 -d false --outDir ${OUT_DIR_ESM5} --importHelpers true --sourceMap`);

/* Inline Styles */
cpx.copySync('./src/**/*.scss', `${OUT_DIR_ESM5}/src`);
cpx.copySync('./src/**/*.html', `${OUT_DIR_ESM5}/src`);

shell.exec(`node_modules/.bin/node-sass -r ${OUT_DIR_ESM5} -o ${OUT_DIR_ESM5}`);

replace({
    regex: '.scss',
    replacement: '.css',
    paths: ['./dist'],
    recursive: true,
    silent: true
});
shell.exec(`node_modules/.bin/ng2-inline -b ${OUT_DIR_ESM5} -r -o .  \"${OUT_DIR_ESM5}/**/*.js\"`);

if (shell.exec(`rollup -c rollup.es.config.js -i ${OUT_DIR_ESM5}/${PACKAGE}.js -o ${ESM5_DIR}/${PACKAGE}.js`).code !== 0) {
    shell.echo(chalk.red(`Error: ESM5 version failed`));
    shell.exit(1);
}

shell.echo(`Run Rollup conversion on package`);
if (shell.exec(`rollup -c rollup.config.js -i ${ESM5_DIR}/${PACKAGE}.js -o ${BUNDLES_DIR}/${PACKAGE}.umd.js`).code !== 0) {
    shell.echo(chalk.red(`Error: Rollup conversion failed`));
    shell.exit(1);
}

shell.echo(`Minifying`);
shell.cd(`${BUNDLES_DIR}`);
shell.exec(`uglifyjs ${PACKAGE}.umd.js -c --comments -o ${PACKAGE}.umd.min.js --source-map "filename='${PACKAGE}.umd.min.js.map', includeSources"`);
shell.cd(`..`);
shell.cd(`..`);

shell.echo(chalk.green(`Bundling completed`));

rimraf.sync(`${NPM_DIR}/package`);
rimraf.sync(`${NPM_DIR}/node_modules`);
rimraf.sync(`${NPM_DIR}/*.{js,js.map}`);
rimraf.sync(`${NPM_DIR}/src/**/*.{js,js.map}`);
rimraf.sync(`${NPM_DIR}/**/*.{scss,css,html}`);

shell.cp(`-Rf`, [`package.json`, `LICENSE.md`, `README.md`], `${NPM_DIR}`);

shell.echo(chalk.green(`End building`));
```

**Comment by robisim74** [comment]
@paullryan Thanks for sharing your solution. It's very interesting. I'd like to try it, but which package is `ng2-inline`? (there are several packages with that name).

**Comment by paullryan** [comment]
@robisim74 it's the [angular2-inline-template-style](https://www.npmjs.com/package/angular2-inline-template-style) package. I'm also playing with pushing to a build directory before running the first ngc call so that the inlining happens before metadata.json.

**Comment by brunano21** [comment]
Hi, any news/progress about this?

**Comment by robisim74** [comment]
@brunano21 This project will continue to be set up like the official Angular packages, until there is an official Angular solution for external templates/styles.

Then, you have the complete control of the building process. and you can follow, for example, suggestion of @paullryan:
- preprocess you scss  or less files (if you have them)
- use an external library _to inline_ the html/css files

At the end, in fact, you must always get the components with the _inlining_ of templates and stylesheets to build an Angular library.

**Comment by paullryan** [comment]
I just realized I never gave my better version that inlines prior to building so it's better for the AOT versions 

```js
"use strict";

const shell = require('shelljs');
const chalk = require('chalk');
const cpx = require('cpx');
const replace = require('replace');
const rimraf = require('rimraf');

const PACKAGE = `time-picker`;
const BUILD_DIR = `build`;
const NPM_DIR = `dist`;
const ESM2015_DIR = `${NPM_DIR}/esm2015`;
const ESM5_DIR = `${NPM_DIR}/esm5`;
const BUNDLES_DIR = `${NPM_DIR}/bundles`;
const OUT_DIR_ESM5 = `${NPM_DIR}/package/esm5`;

shell.echo(`Start building...`);

rimraf.sync(`${BUILD_DIR}/*`);
rimraf.sync(`${NPM_DIR}/*`);
shell.mkdir(`-p`, `./${ESM2015_DIR}`);
shell.mkdir(`-p`, `./${ESM5_DIR}`);
shell.mkdir(`-p`, `./${BUNDLES_DIR}`);
shell.mkdir(`-p`, `./${BUILD_DIR}`);

/* TSLint with Codelyzer */
// https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts
// https://github.com/mgechev/codelyzer
shell.echo(`Start TSLint`);
shell.exec(`tslint -c tslint.json -t stylish src/**/*.ts`);
shell.echo(chalk.green(`TSLint completed`));

cpx.copySync('./src/**/*', `${BUILD_DIR}/src`);
cpx.copySync('./*.ts', `${BUILD_DIR}`);
cpx.copySync('./*.json', `${BUILD_DIR}`);
cpx.copySync('./*.md', `${BUILD_DIR}`);

shell.exec(`node_modules/.bin/node-sass -r ${BUILD_DIR} -o ${BUILD_DIR}`);

replace({
    regex: '.scss',
    replacement: '.css',
    paths: [BUILD_DIR],
    recursive: true,
    silent: true
});

shell.exec(`node_modules/.bin/ng2-inline -b ${BUILD_DIR} -s -r -c -o .  \"${BUILD_DIR}/**/*.ts\"`);

/* AoT compilation */
shell.echo(`Start AoT compilation`);
if (shell.exec(`ngc -p ${BUILD_DIR}/tsconfig-build.json`).code !== 0) {
    shell.echo(chalk.red(`Error: AoT compilation failed`));
    shell.exit(1);
}
shell.echo(chalk.green(`AoT compilation completed`));

/* BUNDLING PACKAGE */
shell.echo(`Start bundling`);
shell.echo(`Rollup package`);
if (shell.exec(`rollup -c rollup.es.config.js -i ${NPM_DIR}/${PACKAGE}.js -o ${ESM2015_DIR}/${PACKAGE}.js`).code !== 0) {
    shell.echo(chalk.red(`Error: Rollup package failed`));
    shell.exit(1);
}

shell.echo(`Produce ESM5 version`);
shell.exec(`ngc -p ${BUILD_DIR}/tsconfig-build.json --target es5 -d false --outDir ${OUT_DIR_ESM5} --importHelpers true --sourceMap`);

if (shell.exec(`rollup -c rollup.es.config.js -i ${OUT_DIR_ESM5}/${PACKAGE}.js -o ${ESM5_DIR}/${PACKAGE}.js`).code !== 0) {
    shell.echo(chalk.red(`Error: ESM5 version failed`));
    shell.exit(1);
}

shell.echo(`Run Rollup conversion on package`);
if (shell.exec(`rollup -c rollup.config.js -i ${ESM5_DIR}/${PACKAGE}.js -o ${BUNDLES_DIR}/${PACKAGE}.umd.js`).code !== 0) {
    shell.echo(chalk.red(`Error: Rollup conversion failed`));
    shell.exit(1);
}

shell.echo(`Minifying`);
shell.cd(`${BUNDLES_DIR}`);
shell.exec(`uglifyjs ${PACKAGE}.umd.js -c --comments -o ${PACKAGE}.umd.min.js --source-map "filename='${PACKAGE}.umd.min.js.map', includeSources"`);
shell.cd(`..`);
shell.cd(`..`);

shell.echo(chalk.green(`Bundling completed`));

rimraf.sync(`${NPM_DIR}/package`);
rimraf.sync(`${NPM_DIR}/node_modules`);
rimraf.sync(`${NPM_DIR}/*.{js,js.map}`);
rimraf.sync(`${NPM_DIR}/src/**/*.{js,js.map}`);
rimraf.sync(`${NPM_DIR}/**/*.{scss,css,html}`);

shell.cp(`-Rf`, [`package.json`, `LICENSE.md`, `README.md`], `${NPM_DIR}`);

shell.echo(chalk.green(`End building`));
```

You'll also need to update the tsconfig-build.json for the new `build` directory structure this creates
```json
{
    "compilerOptions": {
        "rootDir": ".",
        "baseUrl": ".",
        "paths": {
            "@angular/*": [
                "../node_modules/@angular/*"
            ]
        },
        "outDir": "../dist",
        "declaration": true,
        "strict": true,
        "moduleResolution": "node",
        "module": "es2015",
        "target": "es2015",
        "lib": [
            "es2015",
            "dom"
        ],
        "skipLibCheck": true,
        "types": [
            "node"
        ],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "sourceMap": true,
        "inlineSources": true
    },
    "files": [
        "public_api.ts",
        "../node_modules/zone.js/dist/zone.js.d.ts"
    ],
    "angularCompilerOptions": {
        "skipTemplateCodegen": true,
        "annotateForClosureCompiler": true,
        "strictMetadataEmit": true,
        "flatModuleOutFile": "time-picker.js",
        "flatModuleId": "time-picker"
    }
}
```

Plus don't forget to add `/build` to your `.gitignore`

**Comment by brunano21** [comment]
Thank you @paullryan for sharing this. 

@robisim74 do you think to merge this into your repo?

**Comment by robisim74** [comment]
@brunano21 Please read the comment above: https://github.com/robisim74/angular-library-starter/issues/1#issuecomment-354886768

**Comment by dhilt** [comment]
During my investigation of the issue ([SO1](https://stackoverflow.com/questions/48243429/build-angular-module-with-rollup-js-external-html-template-file-wont-work-404), [SO2](https://stackoverflow.com/a/48253259/3211932)) I decided to apply a workaround which may be useful for someone who don't want to use pre-compile solutions. The substantive part is to 

 - rename the template/style source files be adding `.ts` suffix 
 - wrap the template/style contents with exporting default strings
 - direclty import them into the component

**my.component.temlate.html.ts**

```
export default `
<div data-padding-top></div>
...
<div data-padding-bottom></div>
`
```

**my.component.temlate.css.ts**

```
export default `
:host {
  overflow-anchor: none;
  overflow-y: auto;
}
`
```

**my.component.ts**

```
import template from './my.component.temlate.html'
import style from './my.component.temlate.css'

@Component({
  selector: 'app-my-component',
  template: template + '',
  styles: [style + '']
})
```

**Comment by robisim74** [comment]
Based on @paullryan's solution, I added the instructions to adapt the library for inlining of templates and stylesheets: https://github.com/robisim74/angular-library-starter/blob/master/INLINING.md

@paullryan Feel free to contribute.

However, keep in mind that every solution is a temporary workaround, because _ngc_ compiler still does not support inlining of templates & styles: https://github.com/angular/angular/issues/16157

**Comment by kambbado** [comment]
This resolved an issue I had with a .scss file when generating the documentation see compodoc issue [RangeError: Maximum call stack size exceeded](https://github.com/compodoc/compodoc/issues/410)

**Comment by RicardoJBarrios** [comment]
Hello.

Thanks to @paullryan and @robisim74 for the inlining solutions, but what are the changes required to Karma for test?. I have tried adding a raw loader to html, but cannot make it work.

Thanks.

**Comment by robisim74** [comment]
@RicardoJBarrios You can find a lot of documentation on how to configure webpack. However, the `raw-loader` for html files is not sufficient, you must also use a template loader, for example: https://github.com/TheLarkInn/angular2-template-loader

```
                    {
                        test: /\.ts$/,
                        use: [
                            'ts-loader',
                            'angular2-template-loader',
                            'source-map-loader'
                        ]
                    },
                    {
                        test: /\.html$/,
                        use: 'raw-loader'
                    },
```

Please note: using this starter allows complete control of the building process, but assumes that you are familiar with configuring module bundlers such as rollup or webpack, and compilers such as TypeScript and Angular. Otherwise there are other starter who do everything behind the scenes.

Greetings

**Comment by robisim74** [comment]
Since Angular v6, inlining of templates & styles is natively supported.

**Comment by aniruddhadas9** [comment]
For angular 6 onwards you can tell the angular compiler to convert your template html file to inline template during build.

add `"enableResourceInlining": true`  under `angularCompilerOptions` to your `tsconfig.lib.json` file inside your library folder to convert html files to inline template for angular components.


      "angularCompilerOptions": {
        "enableResourceInlining": true
      },
