### ISSUE TITLE
Credits to the author if creating a library

### ISSUE THREAD

**Issue by alejandrocoding** [robisim74/angular-library-starter#11]
Hi there,

First of all, big thanks for this, save a lot of time and it's a great quality, it all run smoothly, well done.

Just a question more than an issue, sorry if this is not the place, feel free to close the ticket.

Do we have to credit you as author of this library or save some link/information/mention to it? I am refactoring things, changing file names, reorganizing a little bit to fit my specs and I just wonder if I need to respect something as I am newbie using this libraries and in licenses in general.

Thanks,

**Comment by robisim74** [comment]
Hi Alejandro,

this starter is distributed under MIT license: https://github.com/robisim74/angular-library-starter/blob/master/LICENSE, so you are welcome to use it and modify it the way you find appropriate.
If you are building your own open source library, you can create your own license: this starter provides only configuration files and not the _library_.
Technically, I think, you should leave in your project only a reference to copyright and license notices: I already added this reference to the entry point: https://github.com/robisim74/angular-library-starter/blob/master/public_api.ts: but you can put the reference where you want it.

To learn more about licensing, visit this link: https://choosealicense.com/

Greetings,
Roberto

**Comment by alejandrocoding** [comment]
Thanks Roberto, it's very helpful :)
