### ISSUE TITLE
Absolute paths tsconfig does not work with testing

### ISSUE THREAD

**Issue by alejandrocoding** [robisim74/angular-library-starter#12]
Hi @robisim74 :)

I am just facing an error when I am using absolute paths for the library I am writing, basically, it does not recognize the paths, although vscode does not complain about it and probably the code runs without problem, I believe it's just the karma-webpack plugin.

The absolute paths in the tsconfig is coming from: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

I think this is not a problem about your library itself but the karma-typescript, anyway I wanted to share with you just in case you know some workaround or anything.

See this image to understand better the error please:

![image](https://cloud.githubusercontent.com/assets/5755545/26736874/ba28006e-47bf-11e7-94b9-d88d494a2c20.png)

Thanks in advance

**Comment by alejandrocoding** [comment]
btw, there it is with PhantomJS but same happen with Chrome

**Comment by robisim74** [comment]
I don't know why you are using absolute paths in the tsconfig file, but if you need to add additional dependencies for testing you should add them to the _spec.bundle.js_ file.

**Comment by alejandrocoding** [comment]
I am not sure if I expressed correctly myself, but what I am trying to do is absolute paths for the tsconfig, as the documentation allows you and as I am using on other projects, it's really powerful and it allows you to structure in a better way your app.

The absolute paths that I am trying to implement are mappings for the tsc, so it makes no sense to add that configuration into a js file, it needs to be within the tsconfig.json file.

What I do not understand why it's not working is the fact that those mappings are working fine for the app itself but not for the testing.

Hope it's clearer now and thanks in advance,

**Comment by robisim74** [comment]
Testing does not use tsc compiler: it uses a loader (in this case _ts-loader_) via webpack.

**Comment by alejandrocoding** [comment]
I know it's using ts-loader, but ts-loader needs a tsconfig.json to know how to transpile the code anyway.

So I wondered why it does not work with the mappings set up in the tsconfig, that was all.

**Comment by robisim74** [comment]
Try to see here: https://github.com/TypeStrong/ts-loader/issues/413

**Comment by alejandrocoding** [comment]
Thanks a lot, I know this is not a problem of your library but that link it's gonna be helpful, If I make it through, I will share it here in case someone else needs it. :)

**Comment by alejandrocoding** [comment]
it solved by alias as said in the link above. So the karma.conf file looks like:

```
webpack: {
            resolve: {
                extensions: ['.ts', '.js'],
                alias: {
                    // same paths than tsconfig.json
                    "@lib/*": __dirname + "/src/",
                    "@entities/*": __dirname + "/src/entities/",
                    "@modules/*": __dirname + "/src/modules/",
                    "@services": __dirname + "/src/services/"
                }
            }
```

**Comment by robisim74** [comment]
Thanks for reporting. Greetings
