### ISSUE TITLE
Dependency with angular-cli

### ISSUE THREAD

**Issue by jotak** [robisim74/angular-library-starter#16]
Hi,

The doc says there's nothing to do while loading the built library from angular-cli. However we need to configure all external dependencies in the downstream app' .angular-cli.json, no? Or maybe there's something I'm doing wrong.

Basically I use this library-starter to build a component library, and need moment.js imported. My downstream app doesn't explicitly require moment.js, it's just needed for the library. But if I don't manually add the link in angular-cli.json it won't load it. So, am I missing something, or is it like I suspect, all 'transitive' dependencies must be explicitly linked downstream?

**Comment by robisim74** [comment]
> we need to configure all external dependencies in the downstream app angular-cli.json

No, you don't need, just import what you need:
`import { ArithmeticModule } from 'angular-library-starter';`

If your library depends on a javascript library (_moment.js_), you need a further configuration: here you can find an example: https://github.com/damienbod/angular-auth-oidc-client. In this library, we manage a javascript library (jsrsasign): see in particular what was done in the _package.json_ and _rollup.config.js_ files. But maybe with _moment.js_ it is still different if it provides the typescript definition file.

In any case the host app must install the javascript library, unless you do not want to include it in your  library (not recommended).

Greetings

**Comment by jotak** [comment]
I see, I tried to go through _rollup.config.js_ before, but I wasn't using the right format to add the lib (was writing `"moment/moment": "moment"` instead of `"moment": "moment"` ; the latter works fine and I can see moment.js correctly included in my output UMD file.

Thanks @robisim74 !
