### ISSUE TITLE
Built with this starter

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-library-starter#17]
I added a section to the README where to insert the libraries built with this starter. 

If you enjoy sharing your project, so you can also compare different solutions obtained from the starter, please make a pr or leave the link below (I will provide to add it).

Greetings,
Roberto

**Comment by orizens** [comment]
hi @robisim74 -
I have 3 npm packages thus far:
https://github.com/orizens/ngx-infinite-scroll 
https://github.com/orizens/ngx-typeahead  
https://github.com/orizens/ng2-youtube-player

**Comment by robisim74** [comment]
@orizens Added. Thanks for sharing.

**Comment by paullryan** [comment]
I guess I'll add https://github.com/nomadreservations/ngx-codemirror it's my rehash of ng2-codemirror for AoT and SSR readiness v1.0.0 will be released today and v1.0.0-rc.3 works as is.
  
_I also have a number of private repos based on this but that's the only public one at the moment._

**Comment by DanielKucal** [comment]
I am currently converting [ngx-store](https://github.com/zoomsphere/ngx-store) to use config from here in https://github.com/zoomsphere/ngx-store/pull/32. Maybe can be added as well :)

**Comment by robisim74** [comment]
@paullryan @DanielKucal When you think that your packages are ready to be published here, let me know or do a pr

**Comment by robisim74** [comment]
Closed due to the #72
