### ISSUE TITLE
Component's public functions not reachable when compiled

### ISSUE THREAD

**Issue by maximelafarie** [robisim74/angular-library-starter#19]
I make a modal npm library thanks to your awesome starter (ngx-smart-modal).
`npm run build` pass without any errors.
I run `npm run pack-lib` to test it in a local fake project to check if it works before sending it to npm.
Then I create this fake project with angular-cli and then run `npm install [path]my-library-[version].tgz`. All is working well for the moment.

I import the library module with `.forRoot()` and a library service in `app.module.ts`.
Then in the `app.component.html` I use the selector of the library component: `<ngx-smart-modal></ngx-smart-modal>`.

In the `ngOnInit()` function of this component I store all this component as a new instance in the imported service I mentioned above.
Each component has public variables and functions.

When I log one of these component instances I have the following:
![image](https://user-images.githubusercontent.com/5319267/28670588-af48f578-72d9-11e7-8d26-26baa2813017.png)

So the variables are reachable from the `app.component.html`. My issue is the functions aren't.

We clearly see the functions are present in the component (NgxSmartModalComponent)
![image](https://user-images.githubusercontent.com/5319267/28670467-130f1f5c-72d9-11e7-991d-7648cf0d97f3.png)

In my `app.component.ts`, I do the following to test if my library's working:
```
...
export class AppComponent {
  title = 'app';

  constructor(public ngxSmartModalService: NgxSmartModalService) {
  }

  openModal(modalId: string) {
    console.log(this.ngxSmartModalService);
    this.ngxSmartModalService.getModal(modalId).open();
  }
}
```
and I call it in `app.component.html`:
```
...
<button (click)="openModal('myModal')">Open myModal</button>

<ngx-smart-modal #myModal [identifier]="'myModal'">
  <h1>Title</h1>
  <p>Some stuff...</p>

  <button (click)="myModal.close()">Close</button>
</ngx-smart-modal>
```

When I click on this button, I run into the following error:
```
AppComponent.html:20 ERROR TypeError: modal.open is not a function
    at AppComponent.webpackJsonp.../../../../../src/app/app.component.ts.AppComponent.openModal (app.component.ts:16)
    at Object.eval [as handleEvent] (AppComponent.html:20)
    at handleEvent (core.es5.js:11995)
    at callWithDebugContext (core.es5.js:13456)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13044)
    at dispatchEvent (core.es5.js:8599)
    at core.es5.js:9210
    at HTMLButtonElement.<anonymous> (platform-browser.es5.js:2651)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:3881)
```

I don't understand this issue given that I declare the `open()` function this way in `NgxSmartModalComponent` (to my mind it's good):
```
public open(top?: boolean): void {
        if (top) {
            this.layerPosition = this.ngxSmartModalService.getHigherIndex();
        }
        this.visible = true;
        this.onOpen.emit(this);
    }
```
and in the compiled file `ngx-smart-modal.es5.js`, it looks like this:
```
/**
     * @param {?=} top
     * @return {?}
     */
    NgxSmartModalComponent.prototype.open = function (top) {
        if (top) {
            this.layerPosition = this.ngxSmartModalService.getHigherIndex();
        }
        this.visible = true;
        this.onOpen.emit(this);
    };
``` 

In the uncompiled library module `ngx-smart-modal.module.ts`, I declare and export the component, that's why I don't understand where this issue come from.
```
@NgModule({
    declarations: [NgxSmartModalComponent],
    exports: [NgxSmartModalComponent],
    imports: [CommonModule, BrowserModule, BrowserAnimationsModule]
})
export class NgxSmartModalModule {

    /**
     * Use in AppModule: new instance of NgxSmartModal.
     */
    public static forRoot(): ModuleWithProviders {
        return {
            ngModule: NgxSmartModalModule,
            providers: [NgxSmartModalService]
        };
    }

    /**
     * Use in features modules with lazy loading: new instance of NgxSmartModal.
     */
    public static forChild(): ModuleWithProviders {
        return {
            ngModule: NgxSmartModalModule,
            providers: [NgxSmartModalService]
        };
    }

}
```

**Comment by robisim74** [comment]
Just some questions:
- Are you using the configuration that I found here: https://github.com/maximelafarie/ngx-smart-modal or the configuration of this starter? and where can I find it to reproduce the problem?
- Are you getting the error in JiT and AoT mode, or only in AoT mode?

**Comment by maximelafarie** [comment]
- Sorry, the repo you saw is the original developed with another solution that is not working properly. I'm currently using your library starter example. Here it is : https://github.com/maximelafarie/ngx-smart-modal-refacto (I just pushed it few seconds ago to let you see the code) 😉 

- Only in JiT for the moment, I not tried to `ng build --prod` my example test project but I'll try it.

**Comment by robisim74** [comment]
Ok, later I'll give it a look and let you know.

**Comment by maximelafarie** [comment]
Thank you a lot.

**Comment by robisim74** [comment]
@maximelafarie 

I noticed that in changing the configuration, you also raised lodash (correctly in my opinion, because you are building a library). But you have to check the new methods. For example, `getModal` method:
```
    public getModal(id: string): NgxSmartModalComponent {
        return _.find(this.modalStack, (o: any) => {
            return o.id === id;
        }).modal;
    }
```
has become:
```
    public getModal(id: string): NgxSmartModalComponent {
        let modal: any = null;
        this.modalStack.forEach((m: any) => m.id === id ? modal = m : false);
        return modal; 
    }
```
that is wrong.

If you change it for example in this way:
```
    public getModal(id: string): NgxSmartModalComponent {
        return this.modalStack.filter((o: any) => {
            return o.id === id;
        })[0].modal;
    }
```
then the library and the example work.

I suggest you to check all the other new methods.

**Comment by maximelafarie** [comment]
@robisim74 Thank you so much for your feedback! I wasn't expected this error could be in the service given that was no error in dev console! Thank you again! 🤘
