### ISSUE TITLE
add "example" directory for development

### ISSUE THREAD

**Issue by orizens** [robisim74/angular-library-starter#24]
hi @robisim74 
I think that an "example" directory is useful when you want to test the package in the browser. 
I created one for  https://github.com/orizens/ngx-infinite-scroll/tree/master/example where i use the final **umd** build. I took the structure from a plunkr - so libraries are loaded via a cdn.

**Comment by paullryan** [comment]
@orizens I find using angular-cli to new a demo/example directory works really well for this and creating this clean as a maintainer means I now have a pretty clear knowledge about the build structure of my demo directory. Might be worth considering just some docs like:

- install the latest angular-cli on your machine
- `ng new demo`
- Open `demo/src/app/app.module.ts` and add your Module
- Configure the render of your example
- et. Voila a demo app to checkin with your package.

**Comment by orizens** [comment]
that means that i'll have a separate project inside the starter with its own package.json.
i want to avoid that and have a simpler setup.

**Comment by paullryan** [comment]
While yes you'll have a seperate project with it's own package.json if you add a demo command like the following to your package.json scripts it takes very little setup from the user (e.g. just run `npm run demo`)

```json
        "demo": "npm run demo:install && npm run demo:serve",
        "demo:watch": "cd demo && npm run start",
        "demo:install": "cd demo && npm install",
        "demo:serve": "npm run demo:watch"
```

And because this in the child path of a directory that contains your module and your already installed node_modules you don't have to add any of your peers to the child package.json. Also your import in app.module.ts is just `import {<your-module>} from '../../../public_api';`

**Comment by paullryan** [comment]
Another added advantage of this is if you do add your peers you can then `cd demo && ng build --prod` from ci and then push the `/demo/dist` folder up to gh-pages as your running demo site for your application.

**Comment by orizens** [comment]
@paullryan 
finally, i embraced the idea of generating a new demo app in "example" directory. 
Then, in order to consume the new build of my lib, after building my lib, i'm using ```npm run pack-lib``` - which creates a tgz file.
Then, in my example directory, i use ```npm i ful-path-to-my-tgz-file```.  
it's nice.

**Comment by paullryan** [comment]
@orizens I added a yalc based quick build and link with watches to my setup that makes it super quick to test the full AoT build path with the demo repo. You can see it in the package.json of https://github.com/nomadreservations/ngx-codemirror

**Comment by orizens** [comment]
thanks for sharing @paullryan 
i did the same.
