### ISSUE TITLE
Upgrade to Angular v5

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-library-starter#25]
Upgrading the building process to Angular v5 when will be released.

**Comment by robisim74** [comment]
Done. See the [Changelog](https://github.com/robisim74/angular-library-starter/blob/master/CHANGELOG.md)

**Comment by randyaa** [comment]
Trying to do the same for my library based on the starter and running into this: https://github.com/rollup/rollup-plugin-commonjs/issues/266

I've played with a bunch of different versions and various approaches but to no avail. any help would be appreciated.

Thanks!

**Comment by robisim74** [comment]
@randyaa I never tried to import lodash with rollup:

- Did it work with the old version of Rollup (0.43)?
- When do you get the error? when compiling or running the library in an app?
- Are you using a `typings.d.ts` file with the following declaration?

`declare module "*";`

and importing it in your `tsconfig-build.json` file?

```
    "files": [
        "public_api.ts",
        "node_modules/zone.js/dist/zone.js.d.ts",
        "typings.d.ts"
    ],
```
It is necessary for commonjs modules.

Then in my opinion you should add `lodash: 'lodash'` to globals, to avoid it being insert in the bundle, and add it as dependency in `package.json`.

I hope this helps.

**Comment by randyaa** [comment]
Yes it was working prior to the upgrade (0.43 as you pointed out). the surrounding configuration hasn't changed.

We don't have a custom typings.d.ts file we instead use `"@types/lodash": "4.14.91",`

**Comment by randyaa** [comment]
ahhh the key seemed to be adding `lodash: 'lodash'` to globals. it seems to work with that thanks!
