### ISSUE TITLE
Please, can you add coverage with istanbul?

### ISSUE THREAD

**Issue by jrgcubano** [robisim74/angular-library-starter#27]
@robisim74 

Maybe using this reporter [karma-coverage-istanbul-reporter](https://github.com/mattlewis92/karma-coverage-istanbul-reporter).

I tried by my self in the library I'm working on [mallorca-ng](https://github.com/MallorcaJS/mallorca-ng). But I can not make your currently karma config work with coverage reporters... 

I was trying to follow this example: 
[angular-calendar karma conf](https://github.com/mattlewis92/angular-calendar/blob/master/karma.conf.ts)

**Comment by jrgcubano** [comment]
Maybe using this reporter [karma-coverage-istanbul-reporter](https://github.com/mattlewis92/karma-coverage-istanbul-reporter)

**Comment by robisim74** [comment]
Added. See this commit to know the differences: https://github.com/robisim74/angular-library-starter/commit/c40d4019c932e3525f8b7ed681766b2dae91c293

Greetings

**Comment by jrgcubano** [comment]
@robisim74 Thanks a lot. Great work with this starter.
