### ISSUE TITLE
How works rollup.config.js globals 'object' for rxjs

### ISSUE THREAD

**Issue by bertrandg** [robisim74/angular-library-starter#29]
Hi,

First, thanks for your great library starter!

I have a small ui library (`angular-split`) and decided to upgrade to your files organisation and bundling.
Everything went good but I've just discover a bug using the UMD module..

In my lib I got these import:
```
import { Observable } from 'rxjs/Observable';
import { Subject } from 'rxjs/Subject';
import 'rxjs/add/operator/debounceTime';
```

So in my `rollup.config.js` I set:

```
const globals = {
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    'rxjs/Observable': 'Rx.Observable',
    'rxjs/Subject': 'Rx.Subject'
};
```

But It fails and I don't really know what this variable is supposed to do.. any idea/help on it?

Here is the generated UMD:
https://unpkg.com/angular-split@0.2.5/bundles/angular-split.umd.js
And a plunker showing the error:
https://plnkr.co/edit/17IWKz?p=preview

**Comment by robisim74** [comment]
Hi @bertrandg,

every RxJS module is an external dependency, so your _globals_ should be:

```
const globals = {
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    'rxjs/Observable': 'Rx',
    'rxjs/Subject': 'Rx',
    'rxjs/add/operator/debounceTime': 'Rx.Observable.prototype'
};
```

**Comment by bertrandg** [comment]
Yes it works now, 
big thanks! :)
