### ISSUE TITLE
Error when produce ESM5 version

### ISSUE THREAD

**Issue by fbrun** [robisim74/angular-library-starter#30]
Hi,

i've a error when build try to produce esm5 version:

`dist/package/esm5/core.js → dist/esm5/core.js...
[!] Error: Could not resolve entry (dist/package/esm5/core.js)
Error: Could not resolve entry (dist/package/esm5/core.js)
    at error (/home/brun/WDIR/edcore/node_modules/rollup/dist/rollup.js:185:14)
    at resolveId.then.id (/home/brun/WDIR/edcore/node_modules/rollup/dist/rollup.js:9807:6)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

Error: ESM5 version failed
`
the core.js is not created.

Do you have any idea ?

**Comment by robisim74** [comment]
If the temporary file `dist/package/esm5/` is not generated, maybe you have an error during the AoT compilation in this line:
```
shell.exec(`ngc -p tsconfig-build.json --target es5 -d false --outDir ${OUT_DIR_ESM5} --importHelpers true --sourceMap`);
```
Any warnings when _Produce ESM5 version_ starts?

**Comment by fbrun** [comment]
I've no warning. I tried to create the package folder with `shell.mkdir('-p', './${OUT_DIR_ESM5}');` in build.js.

The folder is created but error in always the same. It's like the --outDir is not used

I also use angular 4.4.4, not v5.

**Comment by robisim74** [comment]
Using Angular 4.4 could be a problem of TypeScript version.

Try to use the original packages version (Angular 5, TypeScript 2.4.2 etc.) and see what happens.

Actually the starter is configured for Angular v5: to target Angular v4 there is still this branch: https://github.com/robisim74/angular-library-starter/tree/angular_v4

**Comment by robisim74** [comment]
Try also to remove the code of the building process after the compilation: you should see the compiled files in _dist/package/esm5_:

![image](https://user-images.githubusercontent.com/14012361/32550107-320ec9de-c48c-11e7-997f-0235432478aa.png)

**Comment by fbrun** [comment]
I'll move to v4 for test

**Comment by fbrun** [comment]
All is ok now with v4.

Thanks for your help
