### ISSUE TITLE
AOT and umd bundle

### ISSUE THREAD

**Issue by stepet80** [robisim74/angular-library-starter#31]
Is AOT  also supported if u use the library with the umd bundle (by setting the script tag) and by putting the library as an external dependency?

Can you still use import { x } from "library" with AOT?

**Comment by robisim74** [comment]
To be compliant with AoT compilation the umd or es format is indifferent: whatever you need is the metadata file.
Import is always the same: `import { ... } from 'myLibrary`

Are you getting some error?

**Comment by stepet80** [comment]
It complains it can't find the module which is defined as external on the consumer.

**Comment by stepet80** [comment]
Also note  following issue where someone from angular cli says that cli can't work with externals because externals  dont work with aot:
https://github.com/angular/angular-cli

**Comment by robisim74** [comment]
What do you mean with _externals_? Then Angular CLI works with webpack and es5 bundles, not umd.

Please, provide more info about what you are trying to do.

**Comment by stepet80** [comment]
Well for my customer we need to make a webpack angular  consumer app. The js of angular and the library are not allowed to be bundled with the consumer app. So we have to use a cdn mechanism. The way to do this with webpack is to define externals through webpack.

**Comment by stepet80** [comment]
externals: {
  jquery: 'jQuery'
}

**Comment by stepet80** [comment]
So my goal is to have this with aot.

**Comment by robisim74** [comment]
CDN? I do not think AoT can work with it, and it does not depend on this starter.

**Comment by stepet80** [comment]
OK thanks. We will not use aot for now
