### ISSUE TITLE
Rollup build failure

### ISSUE THREAD

**Issue by brunano21** [robisim74/angular-library-starter#34]
While running `npm run build` I get the following build failure:

Run Rollup conversion on package
```
dist/esm5/angular-5-data-table.js → dist/bundles/angular-5-data-table.umd.js...
[!] Error: 'map' is not exported by node_modules\rxjs\operator\map.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules\@angular\forms\esm5\forms.js (10:9)
 8: import { forkJoin } from 'rxjs/observable/forkJoin';
 9: import { fromPromise } from 'rxjs/observable/fromPromise';
10: import { map } from 'rxjs/operator/map';
             ^
11: import { ɵgetDOM } from '@angular/platform-browser';

Error: Rollup conversion failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-5-data-table@0.5.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR!
```
I don't understand what I'm missing.
I have used rollup@5.0.0 and rollup@0.53.1 with no luck. Can anyone give me a hint, please?

**Comment by robisim74** [comment]
Did you add all external dependencies  (Angular packages, RxJS modules etc.) that are you using in your library to _globals_? https://github.com/robisim74/angular-library-starter/blob/master/rollup.config.js

**Comment by brunano21** [comment]
I have actually copied the entire file only. Should I add explicit imports?

At the moment, I have solved adding `modulesOnly: true` into the resolve(), but I'm not really sure if it's right or not.

**Comment by robisim74** [comment]
As I said, and as you can read in README and the internal docs of the rollup file, to build the _umd_ bundle you must add explicitly all the external dependencies.

**Comment by brunano21** [comment]
Ok, will do in that way then. Thank you. Closing.
