### ISSUE TITLE
public_api

### ISSUE THREAD

**Issue by maxisam** [robisim74/angular-library-starter#4]
Thank you for your effort ! I certainly learn a lot from your sharing.

However, I do have more questions.

What is the main purpose of public_api.ts ? Why index.ts is not sufficient ? 

Thx !

**Comment by robisim74** [comment]
I have only reproduced the building process of the official Angular packages: in this way, _public_api.ts_ contains exportable classes, and using the setting _flatModuleOutFile_ in _tsconfig-build_, the _ngc_ compiler is able to create a _index.d.ts_ and an _index.metadata.json_ only (whereas previously it was generated one for each file).

**Comment by maxisam** [comment]
But index.ts can export those classes as well. I still don't understand the need of doing this.

**Comment by robisim74** [comment]
Yes, it can. But Angular _ngc_ compiler works in this way (disclaimer: I have not built it).
