### ISSUE TITLE
adding rollup-plugin-local-resolve plugin to rollup.es to support barrel files (index.ts)

### ISSUE THREAD

**Issue by FortinFred** [robisim74/angular-library-starter#41]
We had issues building our package once we started using barrel files in our package's folders as described at the following page:
https://angular.io/guide/glossary#barrel

Following this thread suggestion fixed the issue.
https://github.com/rollup/rollup/issues/510

We would like to see that included in the template.

npm install rollup-plugin-local-resolve --save-dev

rollup.es.config.js:

`import sourcemaps from 'rollup-plugin-sourcemaps';
import license from 'rollup-plugin-license';
import resolve from 'rollup-plugin-local-resolve';

const path = require('path');

export default {
    output: {
        format: 'es',
        sourcemap: true
    },
    plugins: [
        resolve(),
        sourcemaps(),
        license({
            sourceMap: true,

            banner: {
                file: path.join(__dirname, 'license-banner.txt'),
                encoding: 'utf-8',
            }
        })
    ],
    onwarn: () => { return }
}
`

**Comment by robisim74** [comment]
@FortinFred Thanks for reporting. You are right: actually, a `node resolve` is missing in the `rollup.es.config.js`. But the plugin to implement it is always the same. I did not understand where the need for a different plugin came from: I just tried the `rollup-plugin-node-resolve` plugin and it works correctly.

So I will add `rollup-plugin-node-resolve` as default.

**Comment by FortinFred** [comment]
I'm not quite sure what's happening on my end but when I use "node-resolve" instead of "local-resolve" I get an error like the following:

`Start building...
rm: could not remove directory (code ENOTEMPTY): dist/src/services
rm: could not remove directory (code ENOTEMPTY): dist/src
Start TSLint
TSLint completed
Start AoT compilation
AoT compilation completed
Start bundling
Rollup package

dist/oel-ng-localisateur.js → dist/esm2015/oel-ng-localisateur.js...
[!] Error: 'BehaviorSubject' is not exported by node_modules\rxjs\BehaviorSubject.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
dist\src\stores\localisateur.store.js (7:9)
5: import { Injectable, NgZone } from "@angular/core";
6: import { of } from "rxjs/observable/of";
7: import { BehaviorSubject } from "rxjs/BehaviorSubject";
            ^
8: import { distinctUntilChanged, map, pluck, switchMap, tap } from "rxjs/operators";
9: import { IndexPSService, PointsDeServiceService } from "../services";

Error: Rollup package failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oel-ng-localisateur@0.0.1 build: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oel-ng-localisateur@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\dev\nodejs\npm-cache\_logs\2018-02-05T16_55_00_433Z-debug.log`

My understanding is that this error is the same as the AOT compilation (rollup.config.js) which requires globals to be declared to rollup. 

Example:

`const globals = {
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    'rxjs/observable/bindCallback': 'Rx.Observable',
    'rxjs/observable/fromPromise': 'Rx.Observable',
    'rxjs/observable/forkJoin': 'Rx.Observable',
    'rxjs/observable/of': 'Rx.Observable',
    'rxjs/operators': 'Rx.Observable.prototype',
    'rxjs/operator/filter': 'Rx.Observable.prototype',
    'rxjs/operator/map': 'Rx.Observable.prototype',
    'rxjs/operator/concatMap': 'Rx.Observable.prototype',
    'rxjs/Observable': 'Rx',
    'rxjs/Observer': 'Rx',
    'rxjs/BehaviorSubject': 'Rx',
    'lunr': 'lunr'
};`

If possible, I would prefer to avoid having to manage those librairies in the rollup.es.config.js as well.  When I'm using local.resolve, I have no errors.  Perhaps the package is bigger... I'll double check on that.

**Comment by robisim74** [comment]
You are re-exporting external dependencies in your barrel, and not only your classes: so I think that if you want to avoid errors, and avoid to include them into your bundle, you have to add `rollup-plugin-node-resolve plugin` and also globals/externals properties to `rollup.es.config.js`. But I never tried to do it.

**Comment by FortinFred** [comment]
I'm not quite sure how I'm re-exporting them.  I do export classes with function that returns Observable and those function do use Subject, BehaviourSubject and operators (map, tap, filter).  

Will those be considered as being, implicitely, exported?

Pardon my ignorance, I'm really not a rollup expert.  The only time I ever used it is with this library.

**Comment by robisim74** [comment]
You should try if the `rollup-plugin-node-resolve` plugin and the `globals` solve your problem. Keep in mind that you do not need to duplicate `globals`, you can create a js file with the `globals` constant and import it into your rollup configuration files.
Alternatively: could you post your barrel and an example of a re-exported class that goes wrong?

**Comment by FortinFred** [comment]
Sorry, I'm a bit swomped right now.  Will try to make an example asap.

**Comment by FortinFred** [comment]
I had to rollback on barrel files for now because the ng build --prod command was failing with the following error:
ERROR in : Unexpected value 'undefined' exported by the module 'LocalisateurModule in c:/dev/fe/forms/projet-dcom-ng-noustrouver/node_modules/oel-ng-localisateur/oel-ng-localisateur.d.ts'

**Comment by FortinFred** [comment]
I've moved on to other projects and not sure if this is still an issue for anybody else.  

I will close it since it has no other comments.
