### ISSUE TITLE
@storybook/angular dosen't work with library starter. Any working alternatives?

### ISSUE THREAD

**Issue by Kamilius** [robisim74/angular-library-starter#42]
Hi guys,
trying to setup kind of `sandbox` (`@storybook/angular` - https://storybook.js.org/) for library to be able to develop components in isolation.

Specifically `@storybook/angular` is throwing too many unreadable errors, so looks like it won't work with this project.

Maybe you had similar experience, or are using something with `angular-library-starter` for sandboxing? If so, could you share?

**Comment by robisim74** [comment]
@Kamilius `@storybook/angular` is an independent package to build Angular components. This library is used to create a distribution package of Angular classes.

If you have problems with  `@storybook/angular`, please open a question in the related repo or on StackOverflow.

If you have problems with this starter, please provide a repro o more info.

Greetings
