### ISSUE TITLE
Use library based off this starter in Angular 4.x

### ISSUE THREAD

**Issue by malytskyy** [robisim74/angular-library-starter#43]
Hi, 

Thank you for this great repo, helped me a lot! After I've shared my library, I noticed that it can't be consumed by Angular 4.x application, which seems to be 'by design' according to my research on the internet. Therefore, wanted to ask for advice on how would you recommend to go about creating such library for teams with Angular 4 and 5 at the same time (not sure this is possible at all)? Should I try creating library based on Angular 4 branch of this repo and see if it can be consumed by Angular 5 app as well? I had an impression for the diff between 4 and master branch that new stuff is not backported to Angular 4 branch. Thank you!

**Comment by robisim74** [comment]
Hi @malytskyy,

yes, if you want target Angular 4 and Angular 5, you can use the v4 branch: https://github.com/robisim74/angular-library-starter/tree/angular_v4

Basically, they create the same files, just the package format is different.

Greetings
