### ISSUE TITLE
Library not working with ng build --prod

### ISSUE THREAD

**Issue by JulCesWhat** [robisim74/angular-library-starter#44]
Hi, 

First of all, you library is very helpful for starting to build libraries. I tried to implement a library using your starter pack. It works for almost everything, but not when building it for prod. I was wondering if you could give me a few tips where I am doing wrong. The library is a super simple one so don't know why it wouldn't work. The repo is [here](https://github.com/JulCesWhat/angular5-monaco-editor-loader). Thanks for you help.

**Comment by robisim74** [comment]
Hi @JulCesWhat,

ok I'll give it a look and let you know.

**Comment by robisim74** [comment]
@JulCesWhat,

what's the name of your library? `monaco-editor-loader` or `angular5-monaco-editor-loader`? Because you have two different names inside the library, and it should be only one.

Then you have a scoped package: `@julceswhat/angular5-monaco-editor-loader`. So you must change also in `tsconfig-build.json` file:

```
    "angularCompilerOptions": {
        ...
        "flatModuleOutFile": "monaco-editor-loader.js",
        "flatModuleId": "@julceswhat/angular5-monaco-editor-loader" // complete name of the package
    }
```

and it will work.

Greetings

**Comment by JulCesWhat** [comment]
@robisim74  ...Wow it work! You are really good. Thanks for answering fast. I need to work more with JS tsconfig-build.json files. The name is angular5-monaco-editor-loader. Should I replace every monaco-editor-loader with angular5-monaco-editor-loader? I will also update the library with your new starter code.

**Comment by robisim74** [comment]
In my opinion you should use only one name (the name used in npm package, so in your case `angular5-monaco-editor-loader`): it's easier to maintain and you avoid unexpected errors.

**Comment by JulCesWhat** [comment]
Will do. Thank you for your time and help.
