### ISSUE TITLE
Moment vulnerability alert

### ISSUE THREAD

**Issue by dhilt** [robisim74/angular-library-starter#46]
I've got "potential security vulnerability" message in my project that is built with `angular-library-starter`. I investigated my package-lock.json and found that `rollup-plugin-license` is the cause of the issue: https://github.com/dhilt/ngx-ui-scroll/issues/26.

The solution is to update `rollup-plugin-license` package version to 0.6.0.

**Comment by robisim74** [comment]
Thanks for reporting. I'll update it.

**Comment by robisim74** [comment]
Done.
