### ISSUE TITLE
Provider not found only after running `pack:lib` and installing on my app

### ISSUE THREAD

**Issue by stephengardner** [robisim74/angular-library-starter#47]
I'm creating a module to save Angular's scroll position when navigating between pages.
The module is here, created using this starter: https://github.com/stephengardner/ng-scroll-savior

Using this library starter, I can only get this module to work if I copy the dist folder and include things from that folder.  I can't get this module to work after running `pack:lib` and using the `.tgz`, or when using npm, specifically because I get a "No provider for Router" error.  

Example: after I run `build` from this starter, I can take the `dist` folder, copy it into my example app directory, and include the module, everything works - great!

But when I install the `.tgz` or use npm to install the package, I get a "No provider for Router" error within the app this was installed on.  - The library I'm creating with this starter does utilize the Router, but it's not working as an `npm install`ed package, only as an `import`ed local package.

I'm stumped as to why that would be.

I know this isn't a support forum, but I'm wondering if maybe it has something to do with the `globals` within the `rollup.config.js`, or if there's some way I have to configure this differently?

Again, everything works great when I copy the `dist` folder from this starter.  But when I use the `.tgz` or `npm i ...`, the module errors due to a `No provider for Router` error.

**Comment by robisim74** [comment]
Firstly: follow the docs and correct the errors in your package, for example:
- `https://github.com/robisim74/ng-scroll-savior.git` ? robisim74 is my account...
- Angular router has a different version (^5.2.8)
- `'rxjs/add/operator/filter'` is imported but not added to `globals`
- also, I think you don't need to import the `router` in `ScrollSaviorModule` 
- etc.

Secondly: if after the corrections you still get the error, please provide a demo app to test it.

**Comment by robisim74** [comment]
Closed due to the #72
