### ISSUE TITLE
build with "ng build --prod" fails

### ISSUE THREAD

**Issue by annalen** [robisim74/angular-library-starter#48]
Hallo,
I published your angular-library-starter project on a local npm server.  
Then I imported the angular-library-starter project into my test project. 
When building the project with "_ng build --prod_" I get the following error: 

> ERROR in ./src/app/app.component.ngfactory.js
> Module not found: Error: Can't resolve 'angular-library-starter' in 'C:\tmp\test\src\app'

With "_ng build --no-aot --prod_" everything is going well.

Please can you help me?

**Comment by robisim74** [comment]
What does it mean `published on a local npm server`? Is it a something like a CDN server?

Maybe related to this: https://github.com/robisim74/angular-library-starter/issues/31

**Comment by annalen** [comment]
It is a local verdaccio npm server (https://github.com/verdaccio/verdaccio).

**Comment by robisim74** [comment]
How do you use the published package in your app?

I don't know how _verdaccio_ works: but if you don't install your package in your apps, AoT compilation won't work, and it does not depend on this starter.

**Comment by annalen** [comment]
I am not sure if I understand you correctly.
I published the dist directory with "npm publish" to the local verdaccio server and installed the published starter project like a normal npm package.

Here is a link to my test project with included node_modules as zip file: https://drive.google.com/open?id=1UABjXc4KtQhXoY8Uwdnb2a_dJhdELd09
I'm not sure if that might help you.


Thank you for your help.

**Comment by robisim74** [comment]
Ok, got it. You have a scoped package: `@msag/angular-library-starter`. So you must change in _tsconfig-build.json_ file in the starter:

```
    "angularCompilerOptions": {
        ...
        "flatModuleOutFile": "angular-library-starter.js",
        "flatModuleId": "@msag/angular-library-starter // complete name of the package
    }
```

See also this question: https://github.com/robisim74/angular-library-starter/issues/44 and please, read carefull the README.

Greetings

**Comment by annalen** [comment]
You're the greatest - many thanks for your help and excellent support!
