### ISSUE TITLE
external dependency

### ISSUE THREAD

**Issue by maxisam** [robisim74/angular-library-starter#5]
I tried to use your latest version for my project

https://github.com/maxisam/ngx-clipboard/tree/new_build_es2015_module

But it doesn't work. It turns out during bundling, rollup.js remove the external dependency.

```
exec(`rollup -i ${NPM_DIR}/index.js -o ${MODULES_DIR}/${PACKAGE}.js --sourcemap`, {
    silent: true
});
```
Therefore, the generated code misses this line

```
import * as Clipboard from 'clipboard/index';
```

Any idea how to fix it ?

Thanks

**Comment by robisim74** [comment]
Uhm.. _import *_ seems not work with Rollup: https://github.com/rollup/rollup-plugin-commonjs/issues/157

**Comment by maxisam** [comment]
i guess the only way to do generate a ES2015 bundle is using ngTool/webpack ?

**Comment by robisim74** [comment]
Did you try to use this?

`import 'Clipboard';`

**Comment by maxisam** [comment]
I don't know how it would work in Typescript. The important part is I need to use Clipboard like a class. That's what as Clipboard for.

**Comment by robisim74** [comment]
Ehi @maxisam: did you try this? https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

**Comment by robisim74** [comment]
Keep in mind that when you build the ES2015 package you are not using the `rollup.config.js` file (which is used later for the `umd` file building). So you'll need to add another Rollup config file.

**Comment by maxisam** [comment]
nope. In the end, I ported the clipboard library to Angular. Smaller code base and easier to test. But I will keep in mind and try it sometime.
