### ISSUE TITLE
ng build --prod error when using Module.forRoot()

### ISSUE THREAD

**Issue by krishna-acondy** [robisim74/angular-library-starter#50]
I'm using your starter project to create a library with some common modules, and I must say, it's a great starter that works perfectly for me. I'm facing the following issue though:

One of the modules I have is an `AuthModule` which uses the oidc-client library to implement OAuth 2 authentication. However, a configuration for this client needs to be passed in by the application that consumes my library. I've implemented that using an injection token that's injected into the service.

So I have a `forRoot` method in my `AuthModule` which looks like this:

```
public static forRoot(authConfig: AuthConfig): ModuleWithProviders {
    return {
      ngModule: AuthModule,
      providers: [
        { provide: AUTH_CONFIG, useValue: authConfig },
        AuthService,
        AuthGuard
      ]
    };
  }
```
This works great when I use it in development mode. However, when I try to build my app for production, it errors out with the following error:

```ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'AuthModule' was called.
```

I have looked through the closed issues in this repo, and have changed the `flatModuleId` to match my package name(it is a scoped package). However, I'm still not able to build my app. Any ideas on how I can resolve this?

**Comment by robisim74** [comment]
Hi @krishna-acondy,

I don't think that the error is related to this starter. It seems an AoT common issue. See for example:

https://github.com/angular/angular/issues/14707
https://stackoverflow.com/questions/48283479/how-to-get-rid-of-function-calls-are-not-supported-in-decorators-in-angular-aot
https://stackoverflow.com/questions/49387096/angular-5-function-calls-are-not-supported-in-decorators?noredirect=1&lq=1

**Comment by krishna-acondy** [comment]
Thanks @robisim74. Seems like you're right - this is probably an issue with the Angular AOT compiler. I will look elsewhere for the solution.
