### ISSUE TITLE
library imported in angular-cli project breaks AOT compilation

### ISSUE THREAD

**Issue by santino83** [robisim74/angular-library-starter#54]
Hello,

using this starter I've created a library to share common logic between my applications. I've published the library in my npm repository and then imported it in my angular-cli projects (v4.4.6, so I've used branch v4)

with ng serve I have no problems... but when I run:

ng build --prod --aot

it breaks throwing the error "cannot find MY_MODULE_NAME in app.module.ngfactory.ts". By now, I've deployed the apps with "--no-aot" option, and works... But I would like to resolve the issue. 

Thanks

**Comment by robisim74** [comment]
Did you see #48 and #44?

**Comment by santino83** [comment]
You are right: I have a scoped package and forgot to change the flatModuleId according to this. Thank you very much, great job with this starter and for your help
