### ISSUE TITLE
exported interfaces in library trhows warnings when imported in external projects

### ISSUE THREAD

**Issue by santino83** [robisim74/angular-library-starter#55]
Hello,

Thanks for your work, it's great!. I have made a library with all stuffs like components/services/modules etc... in one file I've put all my types (interfaces) that I use in other classes, and that it's need to be used in external projects when interacting with the library. Eg: if my library is called "company-core", I've the following structure:

public_api.ts -> exporting * from company-core.ts -> exporting * from src/company-core.ts

src/company-core.ts export * from all others folders (src/components, src/moduels, etc..) plus export * from src/company-core.types.ts

in company-core.types.ts I have several interface definitions like:
`export interface ICompanyInterface{ name: string }`

test/builds/packing all ok, so publishing. Then I import this library into my angular-cli application (v4.4.6), and if I try to use the above interface:

`
export class MyComponent{
...
  myField: ICompanyInterface
...
}
`

executing 'ng serve' it throws my a warning like:

> WARNING in ./src/app/modules/my.component.ts
> 97:78-86 "export 'ICompanyInterface' was not found in '@myscopedpackage/company-core'

The strange is that if I use 'ng serve --aot' no warnings are throw. Also, with or without warnings (using or not using --aot flag), the application works correctly.

What am I missing? in package.json I have '"typings": "./company-core.d.ts"' , so in "dist" folder I have company-core.d.ts with all export paths like above

Thanks

**Comment by santino83** [comment]
to clarify: I have the same warnings with --aot flag too. I have checked another library I made using your starter, with interface exported, and it doesn't raise those warnings. package.json/tsconfig-build.json/public_api.ts etc looks the same (except for the module name obviously).

I don't know where to look for

**Comment by robisim74** [comment]
Hi @santino83,

it's weird. Try to do the followings steps:

1. Make sure you are exporting explicitly the interfaces, like in this library:  https://github.com/robisim74/angular-l10n/blob/master/src/angular-l10n.ts

2. Make sure you are using a version of TypeScript in the library and in your Angular CLI app compliant with your Angular version (no warnings during installation)

3. Because it could be a problem of cache (interfaces don't exist in the bundles, they are used only by TypeScript compiler), remove `node_modules` and `package-lock.json` from your Angular CLI app, and reinstall everything

**Comment by santino83** [comment]
I've done all, checking typescript versions, removed node_modules/package-lock in bot library and project dirs, downgrade node/npm versions, upgrading those versions... nothing, same warning ... 

I temporaney published it to github, so you could see the library:

https://github.com/santino83/temp

now I'm using:
typescript 2.3.4
angular 4.4.6
angular-cli 1.4.10
node: 6.4.0
npm: 3.10.3

and got this warnings :

> WARNING in ./src/app/modules/profile/form/abstract-profile-form.component.ts
93:78-86 "export 'IProfile' was not found in '\@ circlecrm/circlecrm-auth'
    at HarmonyImportSpecifierDependency._getErrors (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/Compilation.js:701:24)
    at Compilation.finish (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/Compilation.js:559:9)
    at applyPluginsParallel.err (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/Compiler.js:506:17)
    at /home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/Compilation.js:505:11)
    at processModuleDependencies.err (/home/santino83/GIT/circlecrm/circlecrm-userportal-webapp/node_modules/webpack/lib/Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by robisim74** [comment]
I'll give it a look and let you know.

**Comment by santino83** [comment]
ok, got it: it doesn't work in lazy-loaded modules... if I use the interface in an eager laoded module, it works... in lazy loaded modules (like: modules loaded by router) it doesn't...

**Comment by robisim74** [comment]
It's wired that you get warnings only in lazy loaded modules.

However the library seems correct (I cannot try to build and install it because it requires private packages): I should avoid only `export *` everywhere and I have a doubt on your npm version: 3.10.3 Was it supported by Angular CLI 1.4?

Try to see also this question: https://github.com/angular/angular-cli/issues/2034 (it seems a common Angular CLI problem, i.e. for extended interfaces etc.)

**Comment by santino83** [comment]
I could confirm that the problem is not about your starter, it seems some strange problem with interfaces/extended interfaces when lazy loading... For now, I change my code to use "any" as variable's type, and warning disappeared. I'll see when upgrading to angular 5 or 6 if it could be resolved or not.

Last thing: I tried with different versions of npm/node, checking the correct version of typescript for my cli versions, everything right but still warnings... 

Thank you

**Comment by santino83** [comment]
Well, After googling more around, I've found that if you use your interface with @Input decorator, it throws warnings... But, if you use 

`@Input() public propertyName: YourInterface | null` the warning disappears. So, the problem wasn't lazy loading, but Input decorator. With interfaces it wants (or it's better to have) the alternative null value, probably beacuse when the code is compiled, something it's not able to recognize correctly the variable... I don't know... 

It's a very boring "issue" that seems wouldn't be fixed soon (or never). 

Thank you very much

**Comment by robisim74** [comment]
Thank you for reporting. Greetings
