### ISSUE TITLE
Import warning during test run after upgrade to Angular 6

### ISSUE THREAD

**Issue by dhilt** [robisim74/angular-library-starter#56]
I've just cloned angular-library-starter repo from [ff7ce9b](https://github.com/robisim74/angular-library-starter/commit/ff7ce9b1aac10410254ada663f3a7d79e798ec7f) commit (May 4, 2018), installed npm dependencies, run tests and got

> WARNING in ./node_modules/@angular/core/fesm5/core.js
> System.import() is deprecated and will be removed soon. Use import() instead.
> For more info visit https://webpack.js.org/guides/code-splitting/
>  @ ./node_modules/@angular/core/fesm5/testing.js 5569:15-36 7:0-266 181:28-40 335:60-76 751:16-26 756:2-10 791:37-51 795:35-49 992:56-64 1069:8-23 1147:77-87 1159:16-38 1169:25-31 1170:36-42 1171:29-37 1181:37-58 1196:28-36 1206:34-43 1213:24-32 1248:56-64 1312:41-49 1315:46-54 1328:8-25 1336:24-33 1349:61-71 1353:48-54 1358:55-63
>  @ ./spec.bundle.js
> 

I suppose something is not ok with `require.context` call in spec.bundle.js...

**Comment by robisim74** [comment]
This is a known Angular issue: https://github.com/angular/angular/issues/21560

If you don't want to see the warnings, maybe you can find some workaround here: https://github.com/angular/angular/issues/20357

**Comment by damsorian** [comment]
@robisim74  do you know how to hide the issue with angular-cli?

**Comment by robisim74** [comment]
@damsorian I never got this error using Angular CLI, but only using Webpack 4 + Angular v6. However they are only known warnings.

**Comment by prakasa1904** [comment]
ya, only warning but build file is failed also, no build file created... sad

**Comment by robisim74** [comment]
@prakasa1904 This issue is for warnings during the tests. If you have problems with the build files, open a new issue and provide a repro.

**Comment by robisim74** [comment]
These warnings can be hidden adding this plugin: https://github.com/robisim74/angular-library-starter/blob/master/karma.conf.js#L96-L100

Greetings
