### ISSUE TITLE
Ability to export a theme file.

### ISSUE THREAD

**Issue by harikrishna266** [robisim74/angular-library-starter#57]
Is there a way i can export a theme.scss file.
all the components has a scss file that would have a mixin. 
the library would export a scss file that can be imported and customised like in angular material.

**Comment by robisim74** [comment]
A solution could be the following:

- Bundling SCSS files to one bundled file using a library like https://github.com/SimplrJS/scss-bundle
- Copy the `theme.scss` file to dist folder

**Comment by harikrishna266** [comment]
wow awsome. that worked :)
thanks
