### ISSUE TITLE
ngx-ui-scroll

### ISSUE THREAD

**Issue by dhilt** [robisim74/angular-library-starter#60]
Hi Roberto! Some days ago I released first major version of my lib that is based on your lib-starter: [ngx-ui-scroll](https://github.com/dhilt/ngx-ui-scroll). It uses latest version of lib-starter with some little updates (like [this](https://github.com/dhilt/ngx-ui-scroll/blob/v1.0.1/build.js#L109)).

Beyond expressing my gratitude for your great work, I would ask you, do [ngx-ui-scroll](https://github.com/dhilt/ngx-ui-scroll) have a chance to get into the list of "Built with this starter" libraries which is posted in the README? I can make a PR...

**Comment by robisim74** [comment]
Hi Denis, thanks for sharing!

Yes, make a pr to add your project to the README.

Greetings

**Comment by dhilt** [comment]
@robisim74 It is done (PR https://github.com/robisim74/angular-library-starter/pull/61). By the way, don't you want to add to the list of Contents (in the beginning of README) "Built with this starter" and "Previous versions" sections?

**Comment by robisim74** [comment]
Those two sections are growing... so I think they're better at the end.
However, a graphic effect could be added to highlight theme.
P.S. Good PRs are always welcome!

**Comment by dhilt** [comment]
@robisim74 I meant add them as quick links to the Contents list, like

```
## Contents
* [1 Project structure](#1)
...
* [9 Inlining of templates and stylesheets](#9)
* [Built with this starter](#built-with-this-starter)
* [Previous versions](#previous-versions)
```

or

```
## Contents
* [1 Project structure](#1)
...
* [9 Inlining of templates and stylesheets](#9)
* [10 Built with this starter](#10)
* [11 Previous versions](#11)
```

**Comment by robisim74** [comment]
Only to the list of content... you are right! They are missing.
I like your first option.

**Comment by dhilt** [comment]
@robisim74 Ready to go: https://github.com/robisim74/angular-library-starter/pull/62.

**Comment by robisim74** [comment]
Done. Thanks!

**Comment by dhilt** [comment]
Thank you!
