### ISSUE TITLE
Porting to Bazel

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-library-starter#63]
Since the goal of this project has always been to allow the building of an Angular library as an official, it is time to migrate it to Bazel.

The WIP branch: https://github.com/robisim74/angular-library-starter/tree/bazel

**Plan**
- [X] Create Bazel files for building
- [ ] Add support for scss files
- [X] Move tests under Bazel
- [X] Remove unused dev deps and legacy files
- [ ] Update README

**Problems**
- [ ] `"importHelpers": true` in `tsconfig-build.json` does not work: maybe related to https://github.com/bazelbuild/rules_typescript/issues/252
- [ ] how to remove `external` from the distributed package `bin/angular-library-starter`
- [X] how to remove `amd-module` declaration from `d.ts` files (fixed from Angular v8 beta)
- [ ] how to publish the package `bin/angular-library-starter` (should be used symlink or the user folder?)
- [ ] tests are built but not executed

**Installing**
Requirements:
- NodeJS
- Bazel (https://docs.bazel.build/versions/master/install.html)
- Yarn

The npm package `@bazel/bazel` is not used, because on Windows there are many other settings to do:
- requires MSYS2 Bash to be installed and set up `BAZEL_SH`: https://github.com/bazelbuild/bazel/issues/6462
- requires _patch_ to be installed
- requires VC++ tools to be installed

(a complete guide can be found in TensorFlow: https://www.tensorflow.org/install/source_windows) 

Moreover on Windows:
- `ibazel` for watch mode is still not supported: https://github.com/bazelbuild/bazel-watcher/issues/105
- sometimes the `bash `processes remain hanging, you have to force the cleanup and redo the build or terminate the processes manually

@alexeagle Any suggestions to solve problems would be greatly appreciated

**Comment by alexeagle** [comment]
"time to migrate it to Bazel" - I'm not sure that's true, as you can see there are still rough edges, and we're not advising anyone that it's time to migrate yet. I'm happy to have your feedback but if this is meant as a seed for library authors, I wouldn't recommend pushing users down this path yet. We'll have a better working preview in the Angular 8.0 timeframe (April) and maybe recommend Bazel as default for libraries in 9.0 (fall)

I think some issues above were solved already:
- ibazel subprocesses hanging
- `external/` directory in the package: https://github.com/bazelbuild/rules_nodejs/pull/503
- support for .scss files - this is in the angular-bazel-example and we're adding it to the schematics in https://github.com/angular/angular/pull/28167
- strip amd module names from .d.ts: https://github.com/angular/angular/blob/master/packages/bazel/src/ng_package/packager.ts#L161

I'm curious to know more about your intent here - do you want to help make Angular libraries build with Bazel by default? maybe we can find a way for you to contribute (at least improving the error messages where you got stuck)

**Comment by robisim74** [comment]
@alexeagle  A brief history of this project.

I started this project two years ago, when there was still no official Angular support for libraries and not even ng-packagr: with two objectives: provide a method to build libraries such as official packages and for educational purposes (mine first!)

It's true that it's early, and it's not my intention to push anyone. I would just like to keep up with the official Angular packages: but I can work on open source projects only in my free time, so it will certainly take many months to get to a stable and fully functional version (I hope!)

The point is that if angular-cli to build the app will also provide the option of Bazel, it will be important to also build libraries with Bazel: I think especially to enterprise projects, where the application is often accompanied by custom libraries and the build time is very important. Also for this devs need a project like this, because it is small, developers can easily understand it, expand it and manage it completely.

Meanwhile, thanks for the suggestions: I will try to solve all the problems gradually keeping track here. If you like, I will update you when there will be progress or still blocking problems.

Thanks again in the meantime!

**Comment by robisim74** [comment]
I am closing due to the lack of Angular BuildTools Convergence (19058).
