### ISSUE TITLE
How to add external style

### ISSUE THREAD

**Issue by anjopater** [robisim74/angular-library-starter#69]
Hi, nice template!

I want to add to my template the primeng library dependecy, however i don't see the `angular.json` 
I want to do this setup https://primefaces.org/primeng/showcase/#/setup

I need to add the `angular.json `file? or can I use any specific file in the template ?

bellow an example added in the `angular.json`

![image](https://user-images.githubusercontent.com/19295280/92253089-7c42f980-eea5-11ea-8696-136b1544c2fc.png)

**Comment by robisim74** [comment]
@anjopater This starter does not use _@angular/cli_, so there isn't an _angular.json_: it was created when angular libraries could not yet be created with the _cli_, and requires a thorough knowledge of configuration.

That said, even using the _cli_, the inclusion of styles in _angular.json_ you show is for the app, not for libraries: in fact, external styles should only be imported into the host app.

By the way, you can `import` external style in `.ts` code, or also in your components: https://stackoverflow.com/questions/34542143/load-external-css-into-component

**Comment by anjopater** [comment]
I solved it don´t importing the styles in the `angular.json ` instead i´m using the` style.css` file like this  `import '../other-style.css';` however should be a good idea find a solution using the `angular.json`

**Comment by robisim74** [comment]
Closed due to the #72
