### ISSUE TITLE
test file

### ISSUE THREAD

**Issue by maxisam** [robisim74/angular-library-starter#8]
Should test files live inside of src ?

https://angular.io/docs/ts/latest/guide/style-guide.html#!#application-structure-and-angular-modules

According to document, it seems like we should put test file with source file.

**Comment by robisim74** [comment]
![image](https://cloud.githubusercontent.com/assets/14012361/25403240/088d9ade-29fc-11e7-969d-6d7bfbda1c4a.png)

**Comment by maxisam** [comment]
huh...that is really weird. I didn't notice that until now. I guess Angular team has their own reason. But I'd probably follow the best practice.

**Comment by robisim74** [comment]
I prefer to keep the tests out of the src folder. But I don't think it makes a big difference.

**Comment by maxisam** [comment]
yeah, it is just like tab and space. I prefer to stick with the book not because I like it because it is a way to create convention

**Comment by robisim74** [comment]
Anyway, in the style guide I didn't find that the tests folder should be in the src folder:

> All of the app's code goes in a folder named src

There isn't a reference to tests. Instead I read:

> Do structure the app such that you can Locate code quickly

Then in the testing guide there is the question if to put spec files next to the things they test, or in a tests folder: https://angular.io/docs/ts/latest/guide/testing.html#!#faq
But that depends on what kind of test it is.

**Comment by maxisam** [comment]
no, i didn't mean to put test folder into src folder. I meant put test file next to source file.


> **Why put specs next to the things they test?**
> It's a good idea to put unit test spec files in the same folder as the application source code files that they test:
> 
> Such tests are easy to find.
> You see at a glance if a part of your application lacks tests.
> Nearby tests can reveal how a part works in context.
> When you move the source (inevitable), you remember to move the test.
> When you rename the source file (inevitable), you remember to rename the test file.


But again, it is just a suggestion.

**Comment by robisim74** [comment]
Yes, it is just a suggestion. However if you continue to read, you'll find:

>Application integration specs can test the interactions of multiple parts spread across folders and modules. They don't really belong to any part in particular, so they don't have a natural home next to any one file.

>It's often better to create an appropriate folder for them in the tests directory.

So the difference is between _unit test_ and _integration test_. Ok, in this project there is only one service and one test, so the test could have been next to the service. But in a real scenario, once you've built your library, you usually have a set of _test cases_ and integration tests: it's unusual that a directive or service doesn't interact with others.
Also, in my opinion, when you build and run tests, it's easier to work in the same folder than to get them around for the application.

If you want to put the test files in the src folder, you only need to update the path in the _spec.bundle.js_ file.

I think I will add this note to the documentation.

**Comment by robisim74** [comment]
Added to docs.
