### ISSUE TITLE
Doesn't stop building if there is an error during compilation

### ISSUE THREAD

**Issue by maxisam** [robisim74/angular-library-starter#9]
Here is the [example](https://travis-ci.org/maxisam/ngx-clipboard/builds/228791334?utm_source=github_status&utm_medium=notification).

It would be nice if it can stop building and throw an error, otherwise, we might miss this.

**Comment by robisim74** [comment]
You are right. But I think we should stop the process only for errors during the building, not for TSLint's advices. What do you think about it?

**Comment by maxisam** [comment]
I agree.

**Comment by robisim74** [comment]
Done.
